config/routes.rb
Rails.application.routes.draw do
  root 'departments#index'

  get 'signup', to: 'administrators#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'labs', to: 'labs#index', as: 'labs_index'
  get 'equipment', to: 'equipment#index', as: 'equipment_index'
  get 'components', to: 'components#index', as: 'components_index'
  get 'items', to: 'items#index', as: 'items_index'

  resources :departments_table
  resources :show_labs

  resources :departments, shallow: true do
    resources :assign, only: :show
    resources :labs, shallow: true do
      resources :items
      resources :equipment
      resources :components
    end
  end

  resources :administrators
  resources :roles
  resources :sessions
  resources :rooms
  resources :units
end

app/models/administrator.rb
# frozen_string_literal: true

class Administrator < ApplicationRecord
  belongs_to :department
  has_one :role
  has_secure_password

  validates :name, length: { minimum: 4 }, presence: true
  validates :email, uniqueness: true, presence: true
  validates :role_id, presence: true
  validates :department_id, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/component.rb
class Component < ApplicationRecord
  belongs_to :lab
  validates :component_name, presence: true
  validates :room_id, presence: true
  validates :unit_id, presence: true
end

app/models/department.rb
# frozen_string_literal: true

class Department < ApplicationRecord
  has_many :labs, dependent: :destroy
  has_many :administrators, dependent: :destroy
  has_many :rooms, dependent: :destroy

  validates :department_name, presence: true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :lab
  validates :equipment_name, presence: true
  validates :room_id, presence: true
  validates :serial_number, presence: true
  validates :model_number, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :lab

  validates :item_name, presence: true
  validates :administrator_name, presence: true
  validates :room_id, presence: true
  validates :assigned_to, presence: true
  validates :lab_id, presence: true
  # validates :unit, presence: true
end

app/models/lab.rb
# frozen_string_literal: true

class Lab < ApplicationRecord
  belongs_to :department
  has_many :equipment, dependent: :destroy
  has_many :components, dependent: :destroy
  has_many :rooms
  has_many :items, dependent: :destroy

  validates :lab_name, presence: true
  validates :administrator_id, presence: true
end

app/models/permission.rb
# frozen_string_literal: true

class Permission
  def initialize(administrator)
    allow :sessions, %i[new create destroy]
    allow :departments, %i[index]
    allow :labs, %i[index create]
    allow :equipment, %i[index create]
    allow :components, %i[index create]
    allow :items, %i[index create]
    allow :departments_table, %i[index]
    allow :rooms, %i[index new create]
    allow :units, %i[index new create edit update show destroy]

    if administrator && administrator.role_id == 3 # super administrator 
      allow_all
    elsif administrator && administrator.role_id == 4 # technologist

      allow :departments, %i[show new create edit update] do |department|
        department.id.to_s == administrator.department_id.to_s
      end

      allow :labs, %i[show new edit update destroy] do |lab|
        lab.department_id.to_s == administrator.department_id.to_s
      end

      allow :assign, %i[show] do |lab|
        lab.department_id.to_s == administrator.department_id.to_s
      end

      allow :rooms, %i[show edit update destroy] do |room|
        room.department_id.to_s == administrator.department_id.to_s
      end

      allow :equipment, %i[new update edit show destroy] do |equipment|
        equipment.lab.department_id.to_s == administrator.department_id.to_s
      end

      allow :components, %i[new update edit show destroy] do |component|
        component.lab.department_id.to_s == administrator.department_id.to_s
      end

      allow :items, %i[new update edit show destroy] do |item|
        item.lab.department_id.to_s == administrator.department_id.to_s
      end

      allow :show_labs, %i[show] do |lab|
        lab.department_id.to_s == administrator.department_id.to_s
      end

      allow :departments_table, %i[show] do |departments_table|
        departments_table.id.to_s == administrator.department_id.to_s
      end

      allow :administrators, %i[update edit show] do |admin|
        admin.id.to_s == administrator.id.to_s
      end

    end
  end

  def allow?(controller, action, resource = nil)
    allowed = @allow_all || @allowed_actions[[controller.to_s, action.to_s]]
    allowed && (allowed == true || resource && allowed.call(resource))
  end

  def allow_all
    @allow_all = true
  end

  def allow(controllers, actions, &block)
    @allowed_actions ||= {}
    Array(controllers).each do |controller|
      Array(actions).each do |action|
        @allowed_actions[[controller.to_s, action.to_s]] = block || true
      end
    end
  end
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  validates :role_name, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :department
  validates :room_name, presence: true
  validates :department_id, presence: true
end

app/models/unit.rb
class Unit < ApplicationRecord
  validates :unit_name,  uniqueness: true, presence: true
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :authenticate
  before_action :authorize
  before_action :find_room, only: %i[edit show update destroy]

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def show; end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to rooms_path
      flash[:success] = 'Room Created.'
    else
      flash.now[:error] = @room.errors.full_messages
      render 'new', status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @room.update(room_params)
      redirect_to rooms_path
      flash[:notice] = 'Room Created.'
    else
      flash.now[:error] = @room.errors.full_messages
      render action: 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @room.destroy

    respond_to do |format|
      format.js { render inline: 'location.reload();' }
    end
    flash[:notice] = 'Room Deleted.'
  end

  private

  def find_room
    @room = current_resource
  end

  def room_params
    params.require(:room).permit(:room_name, :department_id)
  end

  def current_resource
    @current_resource ||= Room.find(params[:id]) if params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assign_helper.rb
module AssignHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/show_labs_helper.rb
module ShowLabsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/rooms/_form.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Room details</h2>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <br />
    <%= form_with model: @room, :html=> {:class => 'form-horizontal form-label-left'} do |f| %>
      <div class="item form-group">
        <%= f.label :room_name, "Room Name*" , class: 'col-form-label col-md-3 col-sm-3 label-align' %>
          <div class="col-md-6 col-sm-6 ">
            <%= f.text_field :room_name, class: 'form-control rounded' , placeholder: 'Room Name' ,
              :required=> true %>
          </div>
      </div>
      <div class="item form-group">
        <%= f.label :department_id, "Department Name*" , class: 'col-form-label col-md-3 col-sm-3 label-align' %>
          <div class="col-md-6 col-sm-6 ">
            <% if current_administrator.role_id == 3 %>
              <%= f.collection_select :department_id, Department.order(:department_name),:id,:department_name, { include_blank: "Select Department" }, { class: "form-control rounded" } %>
            <% elsif current_administrator.role_id == 4 %>
              <%= f.hidden_field :department_id, class: 'form-control rounded' , placeholder: 'Department Name' ,
              :required=> true, value: current_administrator.department_id %>
              <input type="department_name" class="form-control rounded" readonly="readonly" placeholder= <%= Department.find(current_administrator.department_id).department_name%>>
            <% end %>
          </div>
      </div>
      <div class="ln_solid"></div>
      <div class="item form-group">
        <div class="col-md-6 col-sm-6 offset-md-3">
          <%= link_to 'Cancel' , rooms_path, class: 'btn btn-warning rounded-pill' %>
          <%= f.submit nil, :class=> 'btn btn-primary rounded-pill' %>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/rooms/edit.html.erb
<h1> Edit Room </h1>

<%= render "form", room: @room %>

app/views/rooms/index.html.erb
<h1>Rooms</h1>
<div class="x_panel">
  <div class="x_title">
    <ul class="nav navbar panel_toolbox float-right">
      <%= link_to '<i class="fa fa-plus pull-right"></i> Add Room' .html_safe, new_room_path, class: 'text-info' %>
    </ul>
    <ul class="nav navbar-right panel_toolbox float-left">
      <li><input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for room ..."
          title="Type in a room name" class="form-control form-control-sm rounded border-info"></li>
      <li><i class="fa fa-search pt-2 pl-2 text-info" aria-hidden="true"></i></li>
    </ul>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
  <div class='table-responsive'>
    <% if @rooms.length==0 %>
      <p>No Rooms Present</p>
      <% else %>
        <table class="table table-sm" id="myTable">
          <caption>List of all Rooms</caption>
          <thead>
            <tr>
              <th scope="col">
                Room Name
              </th>
              <th scope="col">
                Department Name
              </th>
              <th scope="col">
                Equipment Count
              </th>
              <th scope="col">
                Components Count
              </th>
              <th scope="col">
                Created At
              </th>
              <th scope="col" class="text-center">
                Actions
              </th>
            </tr>
          </thead>
          <tbody>
            <% @rooms.each do |room| %>
            <% if room.department_id.to_s == current_administrator.department_id.to_s || current_administrator.role_id == 3 %>
              <tr>
                <td>
                  <%= room.room_name %>
                </td>
                <td>
                  <%= Department.find(room.department_id).department_name %>
                </td>
                <td>
                  <%= Equipment.where(room_id: room.id).all.count %>
                </td>
                <td>
                  <%= Component.where(room_id: room.id).all.count %>
                </td>
                <td>
                  <%= room.created_at.strftime("%Y-%m-%d") %>
                </td>
                <td class="text-center">
                      <%= link_to '<i class="fa fa-eye"></i> View'.html_safe, room_path(room),class: 'mr-3 text-info' %>
                      <% if current_administrator.role_id == 3 %>
                        |<%= link_to '<i class="fa fa-pencil-square-o pull-right"></i> Edit' .html_safe,
                          edit_room_path(room), class: 'mr-3 ml-3 text-warning' %>|
                          <%= link_to '<i class="fa fa-trash-o pull-right"></i> Delete' .html_safe,
                            room_path(room), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                            class: 'ml-3 text-danger' %>
                      <% end %>
                    </td>
              </tr>
              <% end %>
              <% end %>
          </tbody>
        </table>
        <% end %>
  </div>

  <script>
    function myFunction() {
      var input, filter, table, tr, td, i, txtValue;
      input = document.getElementById("myInput");
      filter = input.value.toUpperCase();
      table = document.getElementById("myTable");
      tr = table.getElementsByTagName("tr");
      for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td")[0];
        if (td) {
          txtValue = td.textContent || td.innerText;
          if (txtValue.toUpperCase().indexOf(filter) > -1) {
            tr[i].style.display = "";
          } else {
            tr[i].style.display = "none";
          }
        }
      }
    }
  </script>

app/views/rooms/new.html.erb
<h1>Add Role</h1>

<%= render "form", role: @role %>

app/views/rooms/show.html.erb
<div class="x_panel mt-5">
  <div class="x_title">
    <h2><%= @room.room_name %></h2>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <table class="table">
        <tbody>
            <tr>
                <th scope="row">Room Name</th>
                <td><%= @room.room_name %></td>
            </tr>
            <tr>
                <th scope="row">Department Name</th>
                <td><%= Department.find(@room.department_id).department_name %></td>
            </tr>
            <tr>
                <th scope="row">Equipment Count</th>
                <td><%= Equipment.where(room_id: @room.id).all.count %></td>
            </tr>
            <tr>
                <th scope="row">Components Count</th>
                <td><%= Component.where(room_id: @room.id).all.count %></td>
            </tr>
            <tr>
                <th scope="row">Created At</th>
                <td><%= @room.created_at.strftime("%Y-%m-%d") %></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
            </tr>
        </tbody>
    </table>
    <div class="clearfix"></div>
    <%= link_to 'Back', rooms_path, class: 'btn btn-warning rounded-pill float-right' %>
    <%= link_to '<i class="fa fa-trash-o"></i> Delete' .html_safe,
                      room_path(@room.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                      class: 'btn btn-danger rounded-pill float-left' %>
    <%= link_to '<i class="fa fa-pencil-square-o"></i> Edit' .html_safe,
                    edit_room_path(@room.id), class: 'btn btn-info rounded-pill float-left' %>
</div>