config/routes.rb
Rails.application.routes.draw do
  root 'departments#index'

  get 'signup', to: 'administrators#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'labs', to: 'labs#index', as: 'labs_index'
  get 'equipment', to: 'equipment#index', as: 'equipment_index'
  get 'components', to: 'components#index', as: 'components_index'
  get 'items', to: 'items#index', as: 'items_index'

  resources :departments_table
  resources :show_labs

  resources :departments, shallow: true do
    resources :assign, only: :show
    resources :labs, shallow: true do
      resources :items
      resources :equipment
      resources :components
    end
  end

  resources :administrators
  resources :roles
  resources :sessions
  resources :rooms
  resources :units
end

app/models/administrator.rb
# frozen_string_literal: true

class Administrator < ApplicationRecord
  belongs_to :department
  has_one :role
  has_secure_password

  validates :name, length: { minimum: 4 }, presence: true
  validates :email, uniqueness: true, presence: true
  validates :role_id, presence: true
  validates :department_id, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/component.rb
class Component < ApplicationRecord
  belongs_to :lab
  validates :component_name, presence: true
  validates :room_id, presence: true
  validates :unit_id, presence: true
end

app/models/department.rb
# frozen_string_literal: true

class Department < ApplicationRecord
  has_many :labs, dependent: :destroy
  has_many :administrators, dependent: :destroy
  has_many :rooms, dependent: :destroy

  validates :department_name, presence: true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :lab
  validates :equipment_name, presence: true
  validates :room_id, presence: true
  validates :serial_number, presence: true
  validates :model_number, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :lab

  validates :item_name, presence: true
  validates :administrator_name, presence: true
  validates :room_id, presence: true
  validates :assigned_to, presence: true
  validates :lab_id, presence: true
  # validates :unit, presence: true
end

app/models/lab.rb
# frozen_string_literal: true

class Lab < ApplicationRecord
  belongs_to :department
  has_many :equipment, dependent: :destroy
  has_many :components, dependent: :destroy
  has_many :rooms
  has_many :items, dependent: :destroy

  validates :lab_name, presence: true
  validates :administrator_id, presence: true
end

app/models/permission.rb
# frozen_string_literal: true

class Permission
  def initialize(administrator)
    allow :sessions, %i[new create destroy]
    allow :departments, %i[index]
    allow :labs, %i[index create]
    allow :equipment, %i[index create]
    allow :components, %i[index create]
    allow :items, %i[index create]
    allow :departments_table, %i[index]
    allow :rooms, %i[index new create]
    allow :units, %i[index new create edit update show destroy]

    if administrator && administrator.role_id == 3 # super administrator 
      allow_all
    elsif administrator && administrator.role_id == 4 # technologist

      allow :departments, %i[show new create edit update] do |department|
        department.id.to_s == administrator.department_id.to_s
      end

      allow :labs, %i[show new edit update destroy] do |lab|
        lab.department_id.to_s == administrator.department_id.to_s
      end

      allow :assign, %i[show] do |lab|
        lab.department_id.to_s == administrator.department_id.to_s
      end

      allow :rooms, %i[show edit update destroy] do |room|
        room.department_id.to_s == administrator.department_id.to_s
      end

      allow :equipment, %i[new update edit show destroy] do |equipment|
        equipment.lab.department_id.to_s == administrator.department_id.to_s
      end

      allow :components, %i[new update edit show destroy] do |component|
        component.lab.department_id.to_s == administrator.department_id.to_s
      end

      allow :items, %i[new update edit show destroy] do |item|
        item.lab.department_id.to_s == administrator.department_id.to_s
      end

      allow :show_labs, %i[show] do |lab|
        lab.department_id.to_s == administrator.department_id.to_s
      end

      allow :departments_table, %i[show] do |departments_table|
        departments_table.id.to_s == administrator.department_id.to_s
      end

      allow :administrators, %i[update edit show] do |admin|
        admin.id.to_s == administrator.id.to_s
      end

    end
  end

  def allow?(controller, action, resource = nil)
    allowed = @allow_all || @allowed_actions[[controller.to_s, action.to_s]]
    allowed && (allowed == true || resource && allowed.call(resource))
  end

  def allow_all
    @allow_all = true
  end

  def allow(controllers, actions, &block)
    @allowed_actions ||= {}
    Array(controllers).each do |controller|
      Array(actions).each do |action|
        @allowed_actions[[controller.to_s, action.to_s]] = block || true
      end
    end
  end
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  validates :role_name, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :department
  validates :room_name, presence: true
  validates :department_id, presence: true
end

app/models/unit.rb
class Unit < ApplicationRecord
  validates :unit_name,  uniqueness: true, presence: true
end

app/controllers/labs_controller.rb
# frozen_string_literal: true

class LabsController < ApplicationController
  before_action :authenticate
  before_action :authorize
  before_action :find_lab, only: %i[edit show update destroy]

  def index
    @labs = Lab.all
    return unless params[:sort]

    @labs = Lab.order(params[:sort])
  end

  def show; end

  def new; end

  def create
    @department = Department.find(params[:department_id])
    @lab = @department.labs.new(labs_params)
    if @lab.save
      redirect_to department_path(@department)
      flash[:success] = 'Laboratory Created.'
    else
      redirect_to department_path(@department)
      flash[:error] = @lab.errors.full_messages
    end
  end

  def edit; end

  def update
    if @lab.update(labs_params)
      redirect_to show_lab_path(@lab)
      flash[:notice] = 'Laboratory Updated.'
    else
      flash.now[:error] = @lab.errors.full_messages
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @lab.destroy

    respond_to do |format|
      format.js { render inline: 'location.reload();' }
    end
    flash[:notice] = 'Laboratory Deleted.'
  end

  private

  def find_lab
    @lab = current_resource
  end

  def labs_params
    params.require(:lab).permit(:lab_name, :administrator_id)
  end

  def current_resource
    @current_resource ||= Lab.find(params[:id]) if params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assign_helper.rb
module AssignHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/show_labs_helper.rb
module ShowLabsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/labs/_edit_form.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Laboratory details</h2>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <br />
    <%= form_with model: @lab, :html=> {:class => 'form-horizontal form-label-left'} do |f| %>
      <div class="item form-group">
        <%= f.label :lab_name, "Laboratory Name*" , class: 'col-form-label col-md-3 col-sm-3 label-align' %>
          <div class="col-md-6 col-sm-6 ">
            <%= f.text_field :lab_name, class: 'form-control rounded' , placeholder: 'Laboratory Name' ,
              :required=> true %>
          </div>
      </div>
      <div class="item form-group">
        <%= f.label :administrator_id, "Administrator Name*" , class: 'col-form-label col-md-3 col-sm-3 label-align' %>
          <div class="col-md-6 col-sm-6 ">
           <%= f.collection_select :administrator_id, Administrator.order(:name),:id,:name, { include_blank: "Select Administrator" }, { class: "form-control rounded" } %>
          </div>
      </div>
      <div class="ln_solid"></div>
      <div class="item form-group">
        <div class="col-md-6 col-sm-6 offset-md-3">
          <%= link_to 'Cancel' , labs_index_path, class: 'btn btn-warning rounded-pill' %>
          <%= f.submit nil, :class=> 'btn btn-primary rounded-pill' %>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/labs/_form.html.erb
<%= form_with model: [@department, @department.labs.build ] do |f| %>
  <div class="row justify-content-between">
    <div class="col-auto">
      <div class='row'>
        <div class='col-auto'>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text ">Laboratory</span>
            </div>
              <%= f.text_field :lab_name, class: 'form-control rounded' , placeholder: 'Laboratory Name' ,
            :required=> true %>
          </div>
        </div>
        <div class="col-auto">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text">Administrator Name</span>
            </div>
              <%= f.collection_select :administrator_id, Administrator.where(department_id: @department.id),:id,:name, {
                include_blank: "Select Administrator" }, { class: "form-control rounded" } %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-auto">
      <%= f.submit nil, :class=> 'btn btn-primary rounded-pill' %>
        <%= link_to 'Back' , departments_path, class: 'btn btn-warning rounded-pill' %>
    </div>
  </div>
  <% end %>

  

app/views/labs/_lab.html.erb
<% if current_administrator.id == lab.administrator_id || current_administrator.role_id == 3 %>
<div class='col-auto'>
  <div class="card mt-3" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">
        <%= link_to lab.lab_name, lab %>
      </h5>
      <p class="card-subtitle mb-2 text-muted">
        <%= Administrator.find(lab.administrator_id).name %>
      </p>
      <br>
      <div class="container">
        <div class="row justify-content-between">
          <div class="col">
            <%= link_to "Add Inventory" , lab, class: 'btn btn-info btn-sm rounded-pill' %>
          </div>
          <div class="col">
            <%= link_to "Assign Inventory" , assign_path(lab), class: 'btn btn-info btn-sm rounded-pill' %>
          </div>
        </div>
        <hr>
        <div class="row justify-content-between">
          <% if current_administrator.role_id==3 %>
            <div class="col">
              <%= link_to '<i class="fa fa-eye"></i> View' .html_safe, show_lab_path(lab),class: 'text-info' %>
            </div>
            <div class="col">
              <%= link_to '<i class="fa fa-pencil-square-o pull-right "></i> Edit' .html_safe, edit_lab_path(lab),
                class: 'text-warning' %>
            </div>
            <div class="col">
              <%= link_to '<i class="fa fa-trash-o pull-right"></i> Delete' .html_safe, lab_path(lab), data: {
                turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'text-danger' %>
            </div>
            <% else %>
              <%= link_to '<i class="fa fa-eye"></i> View' .html_safe, show_lab_path(lab),class: 'text-info float-left pl-3' %>
                <%= link_to '<i class="fa fa-pencil-square-o pull-right "></i> Edit' .html_safe, edit_lab_path(lab),
                  class: 'text-warning float-right pr-3' %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/labs/edit.html.erb
<h1> Edit Lab </h1>

<%= render "edit_form", lab: @lab %>

app/views/labs/index.html.erb
<h1>Laboratories</h1>
<div class="x_panel">
  <div class="x_title">
    <h2>Details</h2>
    <ul class="nav navbar-right panel_toolbox">
      <li><input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for laboratory ..."
          title="Type in a laboratory name" class="form-control form-control-sm rounded border-info"></li>
          <li><i class="fa fa-search pt-2 pl-2 text-info" aria-hidden="true"></i></li>
    </ul>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">

  <div class='table-responsive'>
    <% if @labs.length==0 %>
      <p>No Laboratories Present</p>
      <% else %>
        <table class="table table-sm" id="myTable">
          <caption>List of all Laboratories</caption>
          <thead>
            <tr>
              <th scope="col">
                <%= link_to 'Laboratory <i class="fa fa-caret-down" aria-hidden="true"></i>'.html_safe , :sort=> 'lab_name' %>
              </th>
              <th scope="col">
                Department 
              </th>
              <th scope="col">
                Administrator 
              </th>
              <th scope="col">
                <%= link_to 'Created At <i class="fa fa-caret-down" aria-hidden="true"></i>'.html_safe , :sort=> 'created_at' %>
              </th>
              <th scope="col">
                Equipment Count
              </th>
              <th scope="col">
                Components Count
              </th>
              <th scope="col" class="text-center">
                Actions
              </th>
            </tr>
          </thead>
          <tbody>
            <% @labs.each do |lab| %>
                <% if lab.department.id.to_s == current_administrator.department_id.to_s || current_administrator.role_id == 3 %>
                  <tr>
                    <td>
                      <%= lab.lab_name %>
                    </td>
                    <td>
                      <%= Department.find(lab.department_id).department_name if lab.department_id  %>
                    </td>
                    <td>
                      <%= Administrator.find(lab.administrator_id).name if lab.administrator_id  %>
                    </td>
                    <td>
                      <%= lab.created_at.strftime("%Y-%m-%d") %>
                    </td>
                    <td>
                      <%= lab.equipment.count %>
                    </td>
                    <td>
                      <%= lab.components.count %>
                    </td>
                    <td class="text-center">
                      <%= link_to '<i class="fa fa-eye"></i> View'.html_safe, show_lab_path(lab),class: 'mr-3 text-info' %>
                      <% if current_administrator.role_id == 3 %>
                        |<%= link_to '<i class="fa fa-trash-o pull-right"></i> Delete' .html_safe,
                          lab_path(lab), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                          class: 'ml-3 text-danger' %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
          </tbody>
        </table>
        <% end %>
      </div>

          <script>
            function myFunction() {
              var input, filter, table, tr, td, i, txtValue;
              input = document.getElementById("myInput");
              filter = input.value.toUpperCase();
              table = document.getElementById("myTable");
              tr = table.getElementsByTagName("tr");
              for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                  txtValue = td.textContent || td.innerText;
                  if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                  } else {
                    tr[i].style.display = "none";
                  }
                }
              }
            }
          </script>

app/views/labs/show.html.erb
<h1 class='text-info'>
  <%= @lab.lab_name %>
</h1>
<div class="x_panel">
  <div class="x_title">
    <h2 class="text-primary">
      <%= @lab.lab_name + ' Equipment' %>
    </h2>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">


    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active h6" id="equipment-tab" data-toggle="tab" href="#equipment" role="tab"
          aria-controls="equipment" aria-selected="true">Equipment</a>
      </li>
      <li class="nav-item">
        <a class="nav-link h6" id="components-tab" data-toggle="tab" href="#components" role="tab"
          aria-controls="components" aria-selected="false">Components</a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="equipment" role="tabpanel" aria-labelledby="equipment-tab">
      <div class='table-responsive'>
        <% if @lab.equipment.length==0 %>
          <p>No Equipment Present</p>
          <% else %>
            <table class="table table-hover">
            <caption>List of all Laboratory Equipment</caption>
              <thead>
                <tr>
                  <th scope="col">Equipment Name</th>
                  <th scope="col">Make</th>
                  <th scope="col">Serial Number</th>
                  <th scope="col">Model Number</th>
                  <th scope="col">Status</th>
                  <th scope="col">Remarks</th>
                  <th scope="col">Room Location</th>
                  <th scope="col">Date Added</th>
                  <th scope="col">View</th>
                </tr>
              </thead>
              <%= render @lab.equipment %>
            </table>
            <% end %>
      </div>

              <hr />
              <h2 class='pl-2'> Add a Equipment </h2>
              <%= render 'equipment/form' %>

      </div>
      <div class="tab-pane fade" id="components" role="tabpanel" aria-labelledby="components-tab">

      <div class='table-responsive'>
        <% if @lab.components.length==0 %>
          <p>No Components Present</p>
          <% else %>
            <table class="table table-hover">
            <caption>List of all Laboratory Components</caption>
              <thead>
                <tr>
                  <th scope="col">Component Name</th>
                  <th scope="col">Quantity</th>
                  <th scope="col">Unit</th>
                  <th scope="col">Returnable</th>
                  <th scope="col">Date Added</th>
                  <th scope="col">Room Location</th>
                  <th scope="col">Remarks</th>
                  <th scope="col">View</th>
                </tr>
              </thead>
              <%= render @lab.components %>
            </table>
            <% end %>
      </div>
              <hr />
              <h2 class='pl-2'> Add a Component </h2>
              <%= render 'components/form' %>


      </div>
    </div>
  </div>
</div>