config/routes.rb
Rails.application.routes.draw do
  root 'departments#index'

  get 'signup', to: 'administrators#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'labs', to: 'labs#index', as: 'labs_index'
  get 'equipment', to: 'equipment#index', as: 'equipment_index'
  get 'components', to: 'components#index', as: 'components_index'
  get 'items', to: 'items#index', as: 'items_index'

  resources :departments_table
  resources :show_labs

  resources :departments, shallow: true do
    resources :assign, only: :show
    resources :labs, shallow: true do
      resources :items
      resources :equipment
      resources :components
    end
  end

  resources :administrators
  resources :roles
  resources :sessions
  resources :rooms
  resources :units
end

app/models/administrator.rb
# frozen_string_literal: true

class Administrator < ApplicationRecord
  belongs_to :department
  has_one :role
  has_secure_password

  validates :name, length: { minimum: 4 }, presence: true
  validates :email, uniqueness: true, presence: true
  validates :role_id, presence: true
  validates :department_id, presence: true
end

app/models/component.rb
class Component < ApplicationRecord
  belongs_to :lab
  validates :component_name, presence: true
  validates :room_id, presence: true
  validates :unit_id, presence: true
end

app/models/department.rb
# frozen_string_literal: true

class Department < ApplicationRecord
  has_many :labs, dependent: :destroy
  has_many :administrators, dependent: :destroy
  has_many :rooms, dependent: :destroy

  validates :department_name, presence: true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :lab
  validates :equipment_name, presence: true
  validates :room_id, presence: true
  validates :serial_number, presence: true
  validates :model_number, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :lab

  validates :item_name, presence: true
  validates :administrator_name, presence: true
  validates :room_id, presence: true
  validates :assigned_to, presence: true
  validates :lab_id, presence: true
  # validates :unit, presence: true
end

app/models/lab.rb
# frozen_string_literal: true

class Lab < ApplicationRecord
  belongs_to :department
  has_many :equipment, dependent: :destroy
  has_many :components, dependent: :destroy
  has_many :rooms
  has_many :items, dependent: :destroy

  validates :lab_name, presence: true
  validates :administrator_id, presence: true
end

app/models/permission.rb
# frozen_string_literal: true

class Permission
  def initialize(administrator)
    allow :sessions, %i[new create destroy]
    allow :departments, %i[index]
    allow :labs, %i[index create]
    allow :equipment, %i[index create]
    allow :components, %i[index create]
    allow :items, %i[index create]
    allow :departments_table, %i[index]
    allow :rooms, %i[index new create]
    allow :units, %i[index new create edit update show destroy]

    if administrator && administrator.role_id == 3 # super administrator 
      allow_all
    elsif administrator && administrator.role_id == 4 # technologist

      allow :departments, %i[show new create edit update] do |department|
        department.id.to_s == administrator.department_id.to_s
      end

      allow :labs, %i[show new edit update destroy] do |lab|
        lab.department_id.to_s == administrator.department_id.to_s
      end

      allow :assign, %i[show] do |lab|
        lab.department_id.to_s == administrator.department_id.to_s
      end

      allow :rooms, %i[show edit update destroy] do |room|
        room.department_id.to_s == administrator.department_id.to_s
      end

      allow :equipment, %i[new update edit show destroy] do |equipment|
        equipment.lab.department_id.to_s == administrator.department_id.to_s
      end

      allow :components, %i[new update edit show destroy] do |component|
        component.lab.department_id.to_s == administrator.department_id.to_s
      end

      allow :items, %i[new update edit show destroy] do |item|
        item.lab.department_id.to_s == administrator.department_id.to_s
      end

      allow :show_labs, %i[show] do |lab|
        lab.department_id.to_s == administrator.department_id.to_s
      end

      allow :departments_table, %i[show] do |departments_table|
        departments_table.id.to_s == administrator.department_id.to_s
      end

      allow :administrators, %i[update edit show] do |admin|
        admin.id.to_s == administrator.id.to_s
      end

    end
  end

  def allow?(controller, action, resource = nil)
    allowed = @allow_all || @allowed_actions[[controller.to_s, action.to_s]]
    allowed && (allowed == true || resource && allowed.call(resource))
  end

  def allow_all
    @allow_all = true
  end

  def allow(controllers, actions, &block)
    @allowed_actions ||= {}
    Array(controllers).each do |controller|
      Array(actions).each do |action|
        @allowed_actions[[controller.to_s, action.to_s]] = block || true
      end
    end
  end
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  validates :role_name, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :department
  validates :room_name, presence: true
  validates :department_id, presence: true
end

app/models/unit.rb
class Unit < ApplicationRecord
  validates :unit_name,  uniqueness: true, presence: true
end

app/helpers/assign_helper.rb
module AssignHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/show_labs_helper.rb
module ShowLabsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/navigation/_footer.html.erb
        <footer>
          <div class="pull-right">
            PJR132 - Inventory Management</a>
          </div>
          <div class="clearfix"></div>
        </footer>

app/views/layouts/navigation/_sidebar_menu.html.erb
<!-- menu profile quick info -->
<div class="profile clearfix">
  <div class="profile_pic">
    <%= image_tag 'user.png' , alt: 'User' , class: 'img-circle profile_img' %>
  </div>
  <div class="profile_info">
    <span>Welcome,</span>
    <h2>
      <%= current_administrator.name %>
    </h2>
  </div>
</div>
<!-- /menu profile quick info -->
<br />

<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
  <div class="menu_section">
    <ul class="nav side-menu">
      <li>
        <%= link_to '<i class="fa fa-home"></i> Home' .html_safe, departments_path %>
      </li>
    </ul>
    <hr>
    <h3>General</h3>
    <div class="menu_section">
      <ul class="nav side-menu">
        <li><a><i class="fa fa-table"></i> Inventory Tables <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li>
              <%= link_to "Departments" , departments_table_index_path %>
            </li>
            <li>
              <%= link_to "Labs" , labs_index_path %>
            </li>
            <li>
              <%= link_to "Rooms" , rooms_path %>
            </li>
            <li>
              <%= link_to "Equipment" , equipment_index_path %>
            </li>
            <li>
              <%= link_to "Components" , components_index_path %>
            </li>
            <li>
              <%= link_to "Assigned Items" , items_index_path %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
  <% if current_administrator.role_id == 3 %>
    <div class="menu_section">
      <h3>Management</h3>
      <ul class="nav side-menu">
        <li><a><i class="fa fa-user"></i> Administration <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li>
              <%= link_to "Administrators" , administrators_path %>
            </li>
            <li>
              <%= link_to "Roles" , roles_path %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  <% end %>

  <div class="menu_section">
      <h3>Units</h3>
      <ul class="nav side-menu">
        <li><a><i class="fa fa-calculator"></i> Units <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li>
              <%= link_to "Units" , units_path %>
            </li>
          </ul>
        </li>
      </ul>
    </div>

</div>

<!-- /menu footer buttons -->
<div class="sidebar-footer hidden-small">
<%= link_to '<span class="glyphicon glyphicon-user" aria-hidden="true"></span>' .html_safe, administrator_path(current_administrator), data: {
    toggle: 'tooltip' , placement: 'top' }, class: 'float-left' %>
    <%= link_to '<span class="fa fa-building" aria-hidden="true"></span>' .html_safe, departments_path, data: {
    toggle: 'tooltip' , placement: 'top' }, class: 'float-left' %>
<%= link_to '<span class="fa fa-flask" aria-hidden="true"></span>' .html_safe, labs_index_path, data: {
    toggle: 'tooltip' , placement: 'top' }, class: 'float-left' %>    
<%= link_to '<span class="glyphicon glyphicon-off" aria-hidden="true"></span>' .html_safe, logout_path, data: {
    toggle: 'tooltip' , placement: 'top' }, class: 'float-right' %>
</div>
<!-- /menu footer buttons -->
</div>
</div>

app/views/layouts/navigation/_top_navbar.html.erb
<div class="top_nav">
  <div class="nav_menu">
    <div class="nav toggle">
      <a id="menu_toggle"><i class="fa fa-bars"></i></a>
    </div>
    <nav class="nav navbar-nav">
      <ul class=" navbar-right">
        <li class="nav-item dropdown open" style="padding-left: 15px;">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <%= image_tag 'user.png' %>
              <%= current_administrator.name %>
          </a>
          <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
            <%= link_to 'Profile <i class="fa fa-user float-right"></i>'.html_safe, administrator_path(current_administrator.id),class: 'dropdown-item' %>
            <%= link_to 'Log Out <i class="fa fa-sign-out float-right"></i>' .html_safe, logout_path,
              class: 'dropdown-item' %>
          </div>
        </li>
      </ul>
    </nav>
  </div>
</div>

app/views/shared/_messages.html.erb
<% if success %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert" style="display:inline-block; width: 100%;">
    <%= success %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert" style="display:inline-block; width: 100%;">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if error %>
  <div class="alert alert-danger alert-dismissible fade show m-1" role="alert" style="display:inline-block; width: 100%;">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
    <%= error %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>